### ISSUE TITLE
Update to jfr-mappers 1.0.0

### ISSUE THREAD

**Issue by breedx-nr** [newrelic/newrelic-jfr-reporter#16]
jfr-mappers has reached 1.0.0, so we should update the reporter to use that.
Would also be a good opportunity to upgrade to sdk version 0.9.0.

One note: The summarizers API has a breaking change, so don't be surprised.  It's not too bad, though.

**Comment by XiXiaPdx** [comment]
the update has been completed

https://github.com/newrelic/newrelic-jfr-reporter/blob/28e62c7182e847e19cf67eb770faba53c240b147/build.gradle.kts#L39
