### ISSUE TITLE
update readme with metric api uri and eu example

### ISSUE THREAD

**Issue by XiXiaPdx** [newrelic/newrelic-jfr-reporter#9]
metric api uri

https://metric-api.newrelic.com/metric/v1

link to here - https://docs.newrelic.com/docs/telemetry-data-platform/get-data/apis/report-metrics-metric-api
Scroll down to "Endpoint URL"

EU 

https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/get-started/our-eu-us-region-data-centers#

**Comment by jasonjkeller** [comment]
Related: https://github.com/newrelic/newrelic-jfr-core/issues/107

We need to also document these settings for the JFR daemon.
